////////////////////////////////////////////////////////////////////////////////
//number of men/women and odd/even is between 1-19



Qualtrics.SurveyEngine.setEmbeddedData("a1","7");
Qualtrics.SurveyEngine.setEmbeddedData("a2","5");
Qualtrics.SurveyEngine.setEmbeddedData("a3","11");
Qualtrics.SurveyEngine.setEmbeddedData("a4","9");
Qualtrics.SurveyEngine.setEmbeddedData("a5","8");
Qualtrics.SurveyEngine.setEmbeddedData("a6","9");
Qualtrics.SurveyEngine.setEmbeddedData("a7","4");
Qualtrics.SurveyEngine.setEmbeddedData("a8","15");
Qualtrics.SurveyEngine.setEmbeddedData("a9","3");
Qualtrics.SurveyEngine.setEmbeddedData("a10","8");
Qualtrics.SurveyEngine.setEmbeddedData("a11","18");
Qualtrics.SurveyEngine.setEmbeddedData("a12","2");
Qualtrics.SurveyEngine.setEmbeddedData("a13","9");
Qualtrics.SurveyEngine.setEmbeddedData("a14","2");
Qualtrics.SurveyEngine.setEmbeddedData("a15","3");
Qualtrics.SurveyEngine.setEmbeddedData("a16","9");
Qualtrics.SurveyEngine.setEmbeddedData("a17","5");
Qualtrics.SurveyEngine.setEmbeddedData("a18","5");
Qualtrics.SurveyEngine.setEmbeddedData("a19","12");
Qualtrics.SurveyEngine.setEmbeddedData("a20","15");
Qualtrics.SurveyEngine.setEmbeddedData("b1","13");
Qualtrics.SurveyEngine.setEmbeddedData("b2","15");
Qualtrics.SurveyEngine.setEmbeddedData("b3","9");
Qualtrics.SurveyEngine.setEmbeddedData("b4","11");
Qualtrics.SurveyEngine.setEmbeddedData("b5","12");
Qualtrics.SurveyEngine.setEmbeddedData("b6","11");
Qualtrics.SurveyEngine.setEmbeddedData("b7","16");
Qualtrics.SurveyEngine.setEmbeddedData("b8","5");
Qualtrics.SurveyEngine.setEmbeddedData("b9","17");
Qualtrics.SurveyEngine.setEmbeddedData("b10","12");
Qualtrics.SurveyEngine.setEmbeddedData("b11","2");
Qualtrics.SurveyEngine.setEmbeddedData("b12","18");
Qualtrics.SurveyEngine.setEmbeddedData("b13","11");
Qualtrics.SurveyEngine.setEmbeddedData("b14","18");
Qualtrics.SurveyEngine.setEmbeddedData("b15","17");
Qualtrics.SurveyEngine.setEmbeddedData("b16","11");
Qualtrics.SurveyEngine.setEmbeddedData("b17","15");
Qualtrics.SurveyEngine.setEmbeddedData("b18","15");
Qualtrics.SurveyEngine.setEmbeddedData("b19","8");
Qualtrics.SurveyEngine.setEmbeddedData("b20","5");
Qualtrics.SurveyEngine.setEmbeddedData("c1","16");
Qualtrics.SurveyEngine.setEmbeddedData("c2","13");
Qualtrics.SurveyEngine.setEmbeddedData("c3","15");
Qualtrics.SurveyEngine.setEmbeddedData("c4","7");
Qualtrics.SurveyEngine.setEmbeddedData("c5","2");
Qualtrics.SurveyEngine.setEmbeddedData("c6","3");
Qualtrics.SurveyEngine.setEmbeddedData("c7","14");
Qualtrics.SurveyEngine.setEmbeddedData("c8","7");
Qualtrics.SurveyEngine.setEmbeddedData("c9","6");
Qualtrics.SurveyEngine.setEmbeddedData("c10","8");
Qualtrics.SurveyEngine.setEmbeddedData("c11","3");
Qualtrics.SurveyEngine.setEmbeddedData("c12","10");
Qualtrics.SurveyEngine.setEmbeddedData("c13","9");
Qualtrics.SurveyEngine.setEmbeddedData("c14","15");
Qualtrics.SurveyEngine.setEmbeddedData("c15","4");
Qualtrics.SurveyEngine.setEmbeddedData("c16","10");
Qualtrics.SurveyEngine.setEmbeddedData("c17","18");
Qualtrics.SurveyEngine.setEmbeddedData("c18","7");
Qualtrics.SurveyEngine.setEmbeddedData("c19","4");
Qualtrics.SurveyEngine.setEmbeddedData("c20","6");
Qualtrics.SurveyEngine.setEmbeddedData("d1","4");
Qualtrics.SurveyEngine.setEmbeddedData("d2","7");
Qualtrics.SurveyEngine.setEmbeddedData("d3","5");
Qualtrics.SurveyEngine.setEmbeddedData("d4","13");
Qualtrics.SurveyEngine.setEmbeddedData("d5","18");
Qualtrics.SurveyEngine.setEmbeddedData("d6","17");
Qualtrics.SurveyEngine.setEmbeddedData("d7","6");
Qualtrics.SurveyEngine.setEmbeddedData("d8","13");
Qualtrics.SurveyEngine.setEmbeddedData("d9","14");
Qualtrics.SurveyEngine.setEmbeddedData("d10","12");
Qualtrics.SurveyEngine.setEmbeddedData("d11","17");
Qualtrics.SurveyEngine.setEmbeddedData("d12","10");
Qualtrics.SurveyEngine.setEmbeddedData("d13","11");
Qualtrics.SurveyEngine.setEmbeddedData("d14","5");
Qualtrics.SurveyEngine.setEmbeddedData("d15","16");
Qualtrics.SurveyEngine.setEmbeddedData("d16","10");
Qualtrics.SurveyEngine.setEmbeddedData("d17","2");
Qualtrics.SurveyEngine.setEmbeddedData("d18","13");
Qualtrics.SurveyEngine.setEmbeddedData("d19","16");
Qualtrics.SurveyEngine.setEmbeddedData("d20","14");
Qualtrics.SurveyEngine.setEmbeddedData("e1","1");
Qualtrics.SurveyEngine.setEmbeddedData("e2","1");
Qualtrics.SurveyEngine.setEmbeddedData("e3","1");
Qualtrics.SurveyEngine.setEmbeddedData("e4","0");
Qualtrics.SurveyEngine.setEmbeddedData("e5","1");
Qualtrics.SurveyEngine.setEmbeddedData("e6","0");
Qualtrics.SurveyEngine.setEmbeddedData("e7","0");
Qualtrics.SurveyEngine.setEmbeddedData("e8","0");
Qualtrics.SurveyEngine.setEmbeddedData("e9","0");
Qualtrics.SurveyEngine.setEmbeddedData("e10","0");
Qualtrics.SurveyEngine.setEmbeddedData("e11","0");
Qualtrics.SurveyEngine.setEmbeddedData("e12","1");
Qualtrics.SurveyEngine.setEmbeddedData("e13","1");
Qualtrics.SurveyEngine.setEmbeddedData("e14","1");
Qualtrics.SurveyEngine.setEmbeddedData("e15","0");
Qualtrics.SurveyEngine.setEmbeddedData("e16","1");
Qualtrics.SurveyEngine.setEmbeddedData("e17","0");
Qualtrics.SurveyEngine.setEmbeddedData("e18","1");
Qualtrics.SurveyEngine.setEmbeddedData("e19","0");
Qualtrics.SurveyEngine.setEmbeddedData("e20","1");
Qualtrics.SurveyEngine.setEmbeddedData("f1","1");
Qualtrics.SurveyEngine.setEmbeddedData("f2","0");
Qualtrics.SurveyEngine.setEmbeddedData("f3","1");
Qualtrics.SurveyEngine.setEmbeddedData("f4","1");
Qualtrics.SurveyEngine.setEmbeddedData("f5","0");
Qualtrics.SurveyEngine.setEmbeddedData("f6","1");
Qualtrics.SurveyEngine.setEmbeddedData("f7","1");
Qualtrics.SurveyEngine.setEmbeddedData("f8","0");
Qualtrics.SurveyEngine.setEmbeddedData("f9","1");
Qualtrics.SurveyEngine.setEmbeddedData("f10","1");
Qualtrics.SurveyEngine.setEmbeddedData("f11","0");
Qualtrics.SurveyEngine.setEmbeddedData("f12","1");
Qualtrics.SurveyEngine.setEmbeddedData("f13","0");
Qualtrics.SurveyEngine.setEmbeddedData("f14","0");
Qualtrics.SurveyEngine.setEmbeddedData("f15","0");
Qualtrics.SurveyEngine.setEmbeddedData("f16","0");
Qualtrics.SurveyEngine.setEmbeddedData("f17","1");
Qualtrics.SurveyEngine.setEmbeddedData("f18","0");
Qualtrics.SurveyEngine.setEmbeddedData("f19","1");
Qualtrics.SurveyEngine.setEmbeddedData("f20","1");















////////////////////////////////////////////////////////////////////////////////
//number of men/women and odd/even is between 5-15




Qualtrics.SurveyEngine.setEmbeddedData("a1","7");
Qualtrics.SurveyEngine.setEmbeddedData("a2","10");
Qualtrics.SurveyEngine.setEmbeddedData("a3","10");
Qualtrics.SurveyEngine.setEmbeddedData("a4","6");
Qualtrics.SurveyEngine.setEmbeddedData("a5","13");
Qualtrics.SurveyEngine.setEmbeddedData("a6","10");
Qualtrics.SurveyEngine.setEmbeddedData("a7","13");
Qualtrics.SurveyEngine.setEmbeddedData("a8","7");
Qualtrics.SurveyEngine.setEmbeddedData("a9","7");
Qualtrics.SurveyEngine.setEmbeddedData("a10","14");
Qualtrics.SurveyEngine.setEmbeddedData("a11","12");
Qualtrics.SurveyEngine.setEmbeddedData("a12","8");
Qualtrics.SurveyEngine.setEmbeddedData("a13","14");
Qualtrics.SurveyEngine.setEmbeddedData("a14","6");
Qualtrics.SurveyEngine.setEmbeddedData("a15","6");
Qualtrics.SurveyEngine.setEmbeddedData("a16","11");
Qualtrics.SurveyEngine.setEmbeddedData("a17","9");
Qualtrics.SurveyEngine.setEmbeddedData("a18","14");
Qualtrics.SurveyEngine.setEmbeddedData("a19","5");
Qualtrics.SurveyEngine.setEmbeddedData("a20","11");
Qualtrics.SurveyEngine.setEmbeddedData("b1","13");
Qualtrics.SurveyEngine.setEmbeddedData("b2","10");
Qualtrics.SurveyEngine.setEmbeddedData("b3","10");
Qualtrics.SurveyEngine.setEmbeddedData("b4","14");
Qualtrics.SurveyEngine.setEmbeddedData("b5","7");
Qualtrics.SurveyEngine.setEmbeddedData("b6","10");
Qualtrics.SurveyEngine.setEmbeddedData("b7","7");
Qualtrics.SurveyEngine.setEmbeddedData("b8","13");
Qualtrics.SurveyEngine.setEmbeddedData("b9","13");
Qualtrics.SurveyEngine.setEmbeddedData("b10","6");
Qualtrics.SurveyEngine.setEmbeddedData("b11","8");
Qualtrics.SurveyEngine.setEmbeddedData("b12","12");
Qualtrics.SurveyEngine.setEmbeddedData("b13","6");
Qualtrics.SurveyEngine.setEmbeddedData("b14","14");
Qualtrics.SurveyEngine.setEmbeddedData("b15","14");
Qualtrics.SurveyEngine.setEmbeddedData("b16","9");
Qualtrics.SurveyEngine.setEmbeddedData("b17","11");
Qualtrics.SurveyEngine.setEmbeddedData("b18","6");
Qualtrics.SurveyEngine.setEmbeddedData("b19","15");
Qualtrics.SurveyEngine.setEmbeddedData("b20","9");
Qualtrics.SurveyEngine.setEmbeddedData("c1","13");
Qualtrics.SurveyEngine.setEmbeddedData("c2","8");
Qualtrics.SurveyEngine.setEmbeddedData("c3","15");
Qualtrics.SurveyEngine.setEmbeddedData("c4","9");
Qualtrics.SurveyEngine.setEmbeddedData("c5","6");
Qualtrics.SurveyEngine.setEmbeddedData("c6","15");
Qualtrics.SurveyEngine.setEmbeddedData("c7","9");
Qualtrics.SurveyEngine.setEmbeddedData("c8","8");
Qualtrics.SurveyEngine.setEmbeddedData("c9","8");
Qualtrics.SurveyEngine.setEmbeddedData("c10","9");
Qualtrics.SurveyEngine.setEmbeddedData("c11","8");
Qualtrics.SurveyEngine.setEmbeddedData("c12","13");
Qualtrics.SurveyEngine.setEmbeddedData("c13","15");
Qualtrics.SurveyEngine.setEmbeddedData("c14","10");
Qualtrics.SurveyEngine.setEmbeddedData("c15","11");
Qualtrics.SurveyEngine.setEmbeddedData("c16","14");
Qualtrics.SurveyEngine.setEmbeddedData("c17","11");
Qualtrics.SurveyEngine.setEmbeddedData("c18","6");
Qualtrics.SurveyEngine.setEmbeddedData("c19","8");
Qualtrics.SurveyEngine.setEmbeddedData("c20","5");
Qualtrics.SurveyEngine.setEmbeddedData("d1","7");
Qualtrics.SurveyEngine.setEmbeddedData("d2","12");
Qualtrics.SurveyEngine.setEmbeddedData("d3","5");
Qualtrics.SurveyEngine.setEmbeddedData("d4","11");
Qualtrics.SurveyEngine.setEmbeddedData("d5","14");
Qualtrics.SurveyEngine.setEmbeddedData("d6","5");
Qualtrics.SurveyEngine.setEmbeddedData("d7","11");
Qualtrics.SurveyEngine.setEmbeddedData("d8","12");
Qualtrics.SurveyEngine.setEmbeddedData("d9","12");
Qualtrics.SurveyEngine.setEmbeddedData("d10","11");
Qualtrics.SurveyEngine.setEmbeddedData("d11","12");
Qualtrics.SurveyEngine.setEmbeddedData("d12","7");
Qualtrics.SurveyEngine.setEmbeddedData("d13","5");
Qualtrics.SurveyEngine.setEmbeddedData("d14","10");
Qualtrics.SurveyEngine.setEmbeddedData("d15","9");
Qualtrics.SurveyEngine.setEmbeddedData("d16","6");
Qualtrics.SurveyEngine.setEmbeddedData("d17","9");
Qualtrics.SurveyEngine.setEmbeddedData("d18","14");
Qualtrics.SurveyEngine.setEmbeddedData("d19","12");
Qualtrics.SurveyEngine.setEmbeddedData("d20","15");
Qualtrics.SurveyEngine.setEmbeddedData("e1","1");
Qualtrics.SurveyEngine.setEmbeddedData("e2","1");
Qualtrics.SurveyEngine.setEmbeddedData("e3","1");
Qualtrics.SurveyEngine.setEmbeddedData("e4","0");
Qualtrics.SurveyEngine.setEmbeddedData("e5","1");
Qualtrics.SurveyEngine.setEmbeddedData("e6","0");
Qualtrics.SurveyEngine.setEmbeddedData("e7","0");
Qualtrics.SurveyEngine.setEmbeddedData("e8","0");
Qualtrics.SurveyEngine.setEmbeddedData("e9","0");
Qualtrics.SurveyEngine.setEmbeddedData("e10","0");
Qualtrics.SurveyEngine.setEmbeddedData("e11","0");
Qualtrics.SurveyEngine.setEmbeddedData("e12","1");
Qualtrics.SurveyEngine.setEmbeddedData("e13","1");
Qualtrics.SurveyEngine.setEmbeddedData("e14","1");
Qualtrics.SurveyEngine.setEmbeddedData("e15","0");
Qualtrics.SurveyEngine.setEmbeddedData("e16","1");
Qualtrics.SurveyEngine.setEmbeddedData("e17","0");
Qualtrics.SurveyEngine.setEmbeddedData("e18","1");
Qualtrics.SurveyEngine.setEmbeddedData("e19","0");
Qualtrics.SurveyEngine.setEmbeddedData("e20","1");
Qualtrics.SurveyEngine.setEmbeddedData("f1","1");
Qualtrics.SurveyEngine.setEmbeddedData("f2","0");
Qualtrics.SurveyEngine.setEmbeddedData("f3","1");
Qualtrics.SurveyEngine.setEmbeddedData("f4","1");
Qualtrics.SurveyEngine.setEmbeddedData("f5","0");
Qualtrics.SurveyEngine.setEmbeddedData("f6","1");
Qualtrics.SurveyEngine.setEmbeddedData("f7","1");
Qualtrics.SurveyEngine.setEmbeddedData("f8","0");
Qualtrics.SurveyEngine.setEmbeddedData("f9","1");
Qualtrics.SurveyEngine.setEmbeddedData("f10","1");
Qualtrics.SurveyEngine.setEmbeddedData("f11","0");
Qualtrics.SurveyEngine.setEmbeddedData("f12","1");
Qualtrics.SurveyEngine.setEmbeddedData("f13","0");
Qualtrics.SurveyEngine.setEmbeddedData("f14","0");
Qualtrics.SurveyEngine.setEmbeddedData("f15","0");
Qualtrics.SurveyEngine.setEmbeddedData("f16","0");
Qualtrics.SurveyEngine.setEmbeddedData("f17","1");
Qualtrics.SurveyEngine.setEmbeddedData("f18","0");
Qualtrics.SurveyEngine.setEmbeddedData("f19","1");
Qualtrics.SurveyEngine.setEmbeddedData("f20","1");
